FROM python:3.13.11-slim
#this copies from different docker image
COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/

#creates /code directory in the docker image
WORKDIR /code
#python will run from here 
ENV PATH="/code/.venv/bin:$PATH" 

#copies the following files from local to the image 
COPY pyproject.toml .python-version uv.lock ./
#syncs the local to the image
RUN uv sync --locked

RUN pip install pandas pyarrow

COPY ingest_data.py .

ENTRYPOINT ["uv", "run", "python", "ingest_data.py"]